#baseURL = "https://github.com/"
baseURL = "http://example.org/"
languageCode = "zh-CN"
title = "myblog"
theme = "hyde"


## 分页
paginate = 10
paginatePath = "page"

## 侧边栏导航
[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/zntoast"},
      #{Name = "LinkedIn", URL = "https://www.linkedin.com/in/username/"}
  ]

[params]
  description = "个人博客"
  themeColor = "theme-base-0d" 
  #侧边栏为true(右边)
  layoutReverse = false

## 保持分类的原始名字（false会做转小写处理）
#preserveTaxonomyNames = true

## 是否禁止URL Path转小写
#disablePathToLower = true

## 自动检测是否包含中文/日文/韩文，建议设置为true
#hasCJKLanguage = true

## 摘要长度
#summaryLength = 140
